### 1. Create User
### Create User (if needed)
POST http://127.0.0.1:8081/create_user
Content-Type: application/json

{
    "email": "johnhero@example.com",
    "password": "hashedpassword",
    "first_name": "Johnhero",
    "last_name": "Doe",
    "date_of_birth": "1990-01-01",
    "gender": "Male",
    "contact_phone": "1234567890",
    "address": "123 Street"
}


### 2. **Fetch All Users**
# Get All Users
GET http://127.0.0.1:8081/users
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI0NTNlNDNiZS1iMjZlLTQ4NTMtOGY1OS0xM2JhNzU3N2E1NWEiLCJleHAiOjE3Mjg0MDY2NjF9.gIhZadS51yC9mHZtUP7UowN-M4VAiTrEL0fAvWhxY5M


### 3. **Fetch a User by ID**
# You can replace `{id}` with the actual user ID when running the tests.
GET http://127.0.0.1:8081/user/2a956d58-8639-4df8-9f4c-bcd46e07c7dc


### 4. **Fetch a User by Email**
### Get User by Email
GET http://127.0.0.1:8081/user/email/johnhero@example.com
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI0NTNlNDNiZS1iMjZlLTQ4NTMtOGY1OS0xM2JhNzU3N2E1NWEiLCJleHAiOjE3Mjg0MDY2NjF9.gIhZadS51yC9mHZtUP7UowN-M4VAiTrEL0fAvWhxY5M


### 5. **Update a User by ID**
# Replace `{id}` with the actual user ID.
PUT http://127.0.0.1:8081/user/2a956d58-8639-4df8-9f4c-bcd46e07c7dc
Content-Type: application/json

{
  "first_name": "John Updated",
  "last_name": "Doe Updated",
  "contact_phone": "9876543210",
  "address": "456 Updated Street"
}

### 6. **Delete a User by ID**
# Replace `{id}` with the actual user ID.
DELETE http://127.0.0.1:8081/user/2a956d58-8639-4df8-9f4c-bcd46e07c7dc

### 7. **Login
POST http://127.0.0.1:8081/login HTTP/1.1
Content-Type: application/json

{
    "email": "johnhero@example.com",
    "password": "hashedpassword"
}

### 8. Logout by revoking the refresh token
POST http://127.0.0.1:8081/logout HTTP/1.1
Content-Type: application/json

{
    "refresh_token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI0NTNlNDNiZS1iMjZlLTQ4NTMtOGY1OS0xM2JhNzU3N2E1NWEiLCJleHAiOjE3MzA5OTY0Njh9.prrK6zVM-1qVGfS6Wzn35ngikAk487PwKsGXOVgM6xs"
}

### 9. Refresh the token after logout to check revocation:
POST http://127.0.0.1:8081/refresh_token
Content-Type: application/json

{
    "refresh_token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI0NTNlNDNiZS1iMjZlLTQ4NTMtOGY1OS0xM2JhNzU3N2E1NWEiLCJleHAiOjE3MzA5OTY0Njh9.prrK6zVM-1qVGfS6Wzn35ngikAk487PwKsGXOVgM6xs"
}
