### Add Tenant
POST http://127.0.0.1:8081/create_tenant HTTP/1.1
content-type: application/json

{
    "name": "Godswill William",
    "domain": "school.tasknify.com",
    "address": "123 School Street",
    "contact_email": "admin@testschool.com",
    "contact_phone": "123-456-7890",
    "logo_url": null,
    "timezone": "UTC"
}

### Get Tenants
GET http://127.0.0.1:8081/tenants HTTP/1.1

### Create User
POST http://127.0.0.1:8081/create_user HTTP/1.1
content-type: application/json

{
    "email": "johndoe@example.com",
    "password_hash": "hashedpassword",
    "first_name": "John",
    "last_name": "Doe",
    "date_of_birth": "1990-05-20",
    "gender": "Male",
    "contact_phone": "123-456-7890",
    "address": "456 Elm Street"
}

### Get Users
GET http://127.0.0.1:8081/users HTTP/1.1